spring.application.name=Cart
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/cart?createDatabaseIfNoExist=true
spring.datasource.username=postgres
spring.datasource.password=my1234
spring.jpa.hibernate.ddl-auto=update
server.port=8082